// frontend/js/config.js
// Central place to change the backend URL if you run it on a different port.

const API_BASE = "http://localhost:5050/api";

const LOCALES = [
  { code: "ar", label: "العربية", dir: "rtl" },
  { code: "de", label: "Deutsch", dir: "ltr" },
  { code: "en", label: "English", dir: "ltr" },
];

const STAGE_ORDER = [
  "new_sounds", "new_vocabulary", "new_structures", "reading",
  "listening", "speaking", "writing", "grammar_discovery",
  "grammar_explanation", "final_task", "assessment",
];

const STAGE_ICONS = {
  new_sounds: "🔊",
  new_vocabulary: "🧩",
  new_structures: "🔗",
  reading: "📖",
  listening: "🎧",
  speaking: "🗣️",
  writing: "✍️",
  grammar_discovery: "🔍",
  grammar_explanation: "📐",
  final_task: "🎯",
  assessment: "✅",
};

const UI_STRINGS = {
  ar: {
    app_title: "نظام تعلّم اللغات",
    courses: "المسارات",
    levels: "المستويات",
    units: "الوحدات",
    lessons: "الدروس",
    stages: "مراحل الدرس",
    cefr_reference: "مرجع CEFR",
    add_unit: "+ إضافة وحدة",
    add_lesson: "+ إضافة درس",
    edit_content: "تحرير المحتوى",
    save: "حفظ",
    cancel: "إلغاء",
    title_label: "العنوان",
    objective_label: "الهدف",
    description_label: "الوصف",
    instructions_label: "التعليمات",
    content_label: "المحتوى (JSON)",
    mastery_label: "معيار الإتقان",
    min_score_label: "الحد الأدنى للنجاح %",
    no_lessons: "لا توجد دروس بعد في هذه الوحدة.",
    no_units: "لا توجد وحدات بعد في هذا المستوى.",
    select_level: "اختر مستوى من القائمة",
    select_unit: "اختر وحدة من القائمة",
    select_lesson: "اختر درسًا لعرض مراحله",
    content_empty: "لم يُضَف محتوى لهذه المرحلة بعد",
    content_filled: "محتوى مضاف",
    stages_progress: "مراحل مكتملة",
    loading: "جاري التحميل...",
    error_generic: "حدث خطأ. تأكد من تشغيل الخادم (Backend) على المنفذ 5050.",
    locked: "مُقفل",
    skills: "المهارات",
    new_unit_title: "وحدة جديدة",
    new_lesson_title: "درس جديد",
  },
  de: {
    app_title: "Sprachlernsystem",
    courses: "Lernpfade",
    levels: "Niveaus",
    units: "Einheiten",
    lessons: "Lektionen",
    stages: "Lektionsphasen",
    cefr_reference: "GER-Referenz",
    add_unit: "+ Einheit hinzufügen",
    add_lesson: "+ Lektion hinzufügen",
    edit_content: "Inhalt bearbeiten",
    save: "Speichern",
    cancel: "Abbrechen",
    title_label: "Titel",
    objective_label: "Lernziel",
    description_label: "Beschreibung",
    instructions_label: "Anweisungen",
    content_label: "Inhalt (JSON)",
    mastery_label: "Beherrschungskriterium",
    min_score_label: "Mindestpunktzahl %",
    no_lessons: "Noch keine Lektionen in dieser Einheit.",
    no_units: "Noch keine Einheiten in diesem Niveau.",
    select_level: "Wähle ein Niveau aus der Liste",
    select_unit: "Wähle eine Einheit aus der Liste",
    select_lesson: "Wähle eine Lektion, um ihre Phasen zu sehen",
    content_empty: "Für diese Phase wurde noch kein Inhalt hinzugefügt",
    content_filled: "Inhalt vorhanden",
    stages_progress: "abgeschlossene Phasen",
    loading: "Wird geladen...",
    error_generic: "Ein Fehler ist aufgetreten. Stelle sicher, dass das Backend auf Port 5050 läuft.",
    locked: "Gesperrt",
    skills: "Fertigkeiten",
    new_unit_title: "Neue Einheit",
    new_lesson_title: "Neue Lektion",
  },
  en: {
    app_title: "Language Learning System",
    courses: "Tracks",
    levels: "Levels",
    units: "Units",
    lessons: "Lessons",
    stages: "Lesson Stages",
    cefr_reference: "CEFR Reference",
    add_unit: "+ Add Unit",
    add_lesson: "+ Add Lesson",
    edit_content: "Edit Content",
    save: "Save",
    cancel: "Cancel",
    title_label: "Title",
    objective_label: "Objective",
    description_label: "Description",
    instructions_label: "Instructions",
    content_label: "Content (JSON)",
    mastery_label: "Mastery Criteria",
    min_score_label: "Minimum Passing Score %",
    no_lessons: "No lessons yet in this unit.",
    no_units: "No units yet in this level.",
    select_level: "Select a level from the list",
    select_unit: "Select a unit from the list",
    select_lesson: "Select a lesson to see its stages",
    content_empty: "No content authored for this stage yet",
    content_filled: "Content added",
    stages_progress: "stages completed",
    loading: "Loading...",
    error_generic: "Something went wrong. Make sure the backend is running on port 5050.",
    locked: "Locked",
    skills: "Skills",
    new_unit_title: "New Unit",
    new_lesson_title: "New Lesson",
  },
};
